### ISSUE TITLE
ATLParticipantTableViewController select user crash

### ISSUE THREAD

**Issue by msuprovici** [layerhq/Layer-Parse-iOS-Example#11]
ATLParticipantTableViewController shows the users in my parse database.  However when I select a user from the table, I get the following crash:

2015-05-14 16:23:40.055 Iconic[42631:780042] participant: PFUser: xxxxxx, objectId: xxxxx, localId: (null) {
    ACL = "<PFACL: 0x7fdabbf9dff0>";
    ... (each of the fields stored in the Parse object)...

}

2015-05-14 16:18:34.401 Iconic[42552:778392] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSSetM addObject:]: object cannot be nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000105542c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001051d8bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x0000000105469a05 -[__NSSetM addObject:] + 725
	3   Iconic                              0x00000001001ef04b -[ATLConversationViewController existingConversationWithParticipantIdentifiers:] + 155
	4   Iconic                              0x00000001001ed56a -[ATLConversationViewController conversationWithParticipants:] + 394
	5   Iconic                              0x00000001001eae77 -[ATLConversationViewController configureConversationForAddressBar] + 743
	6   Iconic                              0x00000001001ea318 -[ATLConversationViewController addressBarViewController:didSelectParticipant:] + 104
	7   Iconic                              0x0000000100152839 -[ATLAddressBarViewController notifyDelegateOfSelectedParticipants:] + 489
	8   Iconic                              0x000000010015032e -[ATLAddressBarViewController setSelectedParticipants:] + 814
	9   Iconic                              0x000000010014ffba -[ATLAddressBarViewController selectParticipant:] + 202
	10  Iconic                              0x000000010014505a -[LayerChatConversationViewController participantTableViewController:didSelectParticipant:] + 138
	11  Iconic                              0x000000010017ffbe -[ATLParticipantTableViewController tableView:didSelectRowAtIndexPath:] + 478
	12  UIKit                               0x0000000103b57dc9 -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:] + 1293
	13  UIKit                               0x0000000103b57f0a -[UITableView _userSelectRowAtPendingSelectionIndexPath:] + 219
	14  UIKit                               0x0000000103a8a62c _applyBlockToCFArrayCopiedToStack + 314
	15  UIKit                               0x0000000103a8a4a6 _afterCACommitHandler + 533
	16  CoreFoundation                      0x0000000105475ca7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	17  CoreFoundation                      0x0000000105475c00 __CFRunLoopDoObservers + 368
	18  CoreFoundation                      0x000000010546ba33 __CFRunLoopRun + 1123
	19  CoreFoundation                      0x000000010546b366 CFRunLoopRunSpecific + 470
	20  GraphicsServices                    0x0000000106af0a3e GSEventRunModal + 161
	21  UIKit                               0x0000000103a66900 UIApplicationMain + 1282
	22  Iconic                              0x000000010021c18f main + 111
	23  libdyld.dylib                       0x0000000105f85145 start + 1
	24  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

Any advice on where to go from here?

**Comment by kmahal** [comment]
@msuprovici it's trying to add a nil object.  Set break points at every method in the call stack, from when you select a user to where it crashes, and find out when the object becomes nil.

**Comment by msuprovici** [comment]
Thanks @kmahal The crash seems is taking place in [participants addObject:participant] in the  AltAddressBarViewController method bellow:

- (void)selectParticipant:(id<ATLParticipant>)participant
{
    if (!participant) return;

    NSMutableOrderedSet *participants = [NSMutableOrderedSet orderedSetWithOrderedSet:self.selectedParticipants];
    [participants addObject:participant];  <---- crash
    self.selectedParticipants = participants;
}

The logs show me the selected participant object and all the data stored in parse but the localId is null on all objects. Does layer create a localId?  Also does the user need to authenticate with layer every time they run the app or just on registration?

**Comment by msuprovici** [comment]
@kmahal  After investigating this more, it looks like the crash is taking place in - (LYRConversation *)conversationWithParticipants:(NSSet *)participants


    NSSet *participantIdentifiers = [participants valueForKey:@"participantIdentifier"];
    conversation = [self existingConversationWithParticipantIdentifiers:participantIdentifiers]; <-crash

I could not determine where you set the @"participantIdentifier" in the demo project.

**Comment by kmahal** [comment]
@msuprovici Please see https://developer.layer.com/docs/integration#authentication.  Assuming your objects are `PFUser` instances, you should be using their `objectId` property to authenticate a client.  You must also ensure that your `PFUser` objects adhere to the `ATLParticipant` protocol, which the app already provides for you but you can customize.  `localId` is managed by your (what I assume are) Parse objects and should not matter for this.

**Comment by msuprovici** [comment]
@kmahal Yup, that's what I'm doing.  I'm using the userManger and PFUser+ATLParticipant classes.  Does the user need to authenticate with layer every time the app runs or just on registration?

**Comment by agameofprivacy** [comment]
@msuprovici did you ever find a solution? NSLog was able to print my participant object as not nil right before the addObject method.. Any help would be much appreciated!

    NSLog(@"participant %@", participant);
    [participants addObject:participant];

**Comment by glaksmono** [comment]
@msuprovici I'm wondering how do you solve this?

**Comment by msuprovici** [comment]
@glaksmono  I ended up cashing the layer client object after authenticating it and used that object throughout my project.  Not a great solution, but it seems to have revolved the issue.

**Comment by glaksmono** [comment]
@msuprovici I figured it out, I realized that apparently the `_layerClient` on `ATLAddressBarController` was `nil`, so I dig deeper on what caused that. The bottom line is basically you need to ensure that the instance of the `LayerClient` that is used at the moment of initiating the message isn't `nil`

```
    @IBAction func onContact(sender: UIButton) {
        let controller = ConversationViewController(layerClient: self.layerClient) // self.layerClient was nil
        controller.displaysAddressBar = true
        self.navigationController!.pushViewController(controller, animated: true)
    }
```
