### ISSUE TITLE
NSCache VS. NSKeyedArchiver

### ISSUE THREAD

**Issue by stefanocdn** [layerhq/Layer-Parse-iOS-Example#13]
Hi, is there was a reason that Atlas-Messenger-iOS uses NSKeyedArchiver to store users whereas this project uses NSCache?Is there a recommend approach for storing users?

Also, it enables Parse Local Datastore, but none of its methods are ever called..

**Comment by kmahal** [comment]
@stefanocdn We previously were using the local datastore but decided against it - that line should be taken out.  Feel free to submit a PR for the fix.  `NSCache` and `NSKeyedArchiver` are used for different purposes.  `NSKeyedArchiver` is used when writing files to a path for deep persistence, while `NSCache` just holds an in-memory reference to saved objects.  We don't need to deeply persist any of the objects, so the cache works best in this case.
