### ISSUE TITLE
The sent pictures on chat are greyed out.

### ISSUE THREAD

**Issue by kwkhaw** [layerhq/Layer-Parse-iOS-Example#15]
![78d267b6-103b-11e5-89ca-fbe3592e8beb](https://cloud.githubusercontent.com/assets/2577532/8108674/7b3c3cea-1084-11e5-8f64-101b94d1ee24.png)

Reported by EMidee66 on Layer-Parse-iOS-Swift-Example (https://github.com/kwkhaw/Layer-Parse-iOS-Swift-Example/issues/1), but I found Layer-Parse-iOS-Example has the same issue as well.

**Comment by khanhvu161188** [comment]
It worked for me if i set these value:
**Auto-download Size**
`self.layerClient.autodownloadMaximumContentSize = 1024 * 100;`
and 
**Auto-download MIME Types**
`self.layerClient.autodownloadMIMETypes = [NSSet setWithObjects:@"image/jpeg", nil];`

**Comment by kwkhaw** [comment]
@khanhvu161188 yeah, it works! Thanks. :+1:
