### ISSUE TITLE
Can't Sign In -- "generateToken" Parse Cloud Code function fails

### ISSUE THREAD

**Issue by ptsimpso** [layerhq/Layer-Parse-iOS-Example#21]
I set up the Parse Cloud Code according to the documentation, however, the app always hangs up on this function. Error log output is as follows:

Parse Cloud function failed to be called to generate token with error: Error Domain=Parse Code=141 "Uncaught init failed:TypeError: Cannot read property 'xy' of undefined"

I believe I've added all of the necessary keys.

**Comment by DmitryBulaienko** [comment]
For those who are still having this issue, please see https://github.com/layerhq/layer-parse-module

**Comment by liruqi** [comment]
Me too
