### ISSUE TITLE
loaded Failed to connect to Layer

### ISSUE THREAD

**Issue by thaamidi** [layerhq/Layer-Parse-iOS-Example#25]
I'm trying to do the Swift example and I've checked all my keys everything looks good, I don't why I couldn't connect to Layer. 

Help please!.

**Comment by thaamidi** [comment]
These are the errors:
1-
LayerKit client v0.17.4 loaded 
Failed to connect to Layer: Optional(Error Domain=SPDYSocketErrorDomain Code=7 "No endpoints available, unable to connect socket" UserInfo={NSLocalizedDescription=No endpoints available, unable to connect socket})

2-
LayerKit client v0.17.4 loaded 
Failed to connect to Layer: Optional(Error Domain=com.layer.LayerKit.Errors Code=6000

**Comment by maju6406** [comment]
Make sure you've properly configured your Info.plist:
https://support.layer.com/hc/en-us/articles/205034154-Are-there-any-known-issues-with-iOS-9-

**Comment by Daheahty** [comment]
Hi,

I am getting the same 'No end points available' error as above. I have deployed the parse module and can see the Heroku app in the Webhook section of Parse and can see the generateToken method listed on the same page both have a status of good. I have uploaded my plist with the following but still get the error.

Any help would be appreciated.

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>storage.googleapis.com</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSExceptionRequiresForwardSecrecy</key>
                <false/>
            </dict>
            <key>authn.lyr8.net</key>
            <dict>
                <key>NSExceptionAllowsInsecureHTTPLoads</key>
                <true/>
            </dict>
            <key>sync.lyr8.net</key>
            <dict>
                <key>NSExceptionAllowsInsecureHTTPLoads</key>
                <true/>
            </dict>
            <key>conf.lyr8.net</key>
            <dict>
                <key>NSExceptionAllowsInsecureHTTPLoads</key>
                <true/>
            </dict>
            <key>certs.lyr8.net</key>
            <dict>
                <key>NSExceptionAllowsInsecureHTTPLoads</key>
                <true/>
            </dict>
        </dict>
    </dict>
 
 
 
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>location</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
</dict>
</plist>




Exact Error: - 

2016-01-13 16:29:35.693 Layer-Parse-iOS-Swift-Example[25858:600481] LayerKit client v0.17.6 loaded
Failed to connect to Layer: Optional(Error Domain=SPDYSocketErrorDomain Code=7 "No endpoints available, unable to connect socket" UserInfo={NSLocalizedDescription=No endpoints available, unable to connect socket})

**Comment by Leomax004** [comment]
Finally able to solve this issue.
If you are using Ios-9,then you have to add some ATS exception in your plist manually from the below link:
 [](https://support.layer.com/hc/en-us/articles/205034154-Are-there-any-known-issues-with-iOS-9-)
just copy & paste into the plist.
If you are still getting the same error,then you have to Reset the Network settings of your Device
i:e:-  Settings->General->Reset->Reset Network settings.
that's solve

**Comment by Leomax004** [comment]
Finally able to solve this issue.
If you are using Ios-9,then you have to add some ATS exception in your plist manually from the below link:
 [https://support.layer.com/hc/en-us/articles/205034154-Are-there-any-known-issues-with-iOS-9-]()
just copy & paste into the plist.
If you are still getting the same error,then you have to Reset the Network settings of your Device
i:e:-  Settings->General->Reset->Reset Network settings.
that's solve
