### ISSUE TITLE
ATLConversationViewController crash when reloading collection view after message always crashes.

### ISSUE THREAD

**Issue by davidolesch** [layerhq/Layer-Parse-iOS-Example#8]
I've followed the steps in the README and only modified the keys in the iOS source code however whenever I send a message the app crashes as it performs a `reloadItemsAtIndexPaths:` on line 937 of ATLConversationViewController.

In the console I'm seeing 

```
*** Assertion failure in -[ATLConversationCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:], /SourceCache/UIKit_Sim/UIKit-3347.44/UICollectionView.m:3870
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete item 6 from section 0 which only contains 0 items before the update'
```

Replacing `reloadItemsAtIndexPaths:` with `reloadData` fixes the problem but there's some underlying problem that needs to be fixed. 

Has anyone else experienced this? Is this a new problem with the 8.3 base SDK?

**Comment by davidolesch** [comment]
The crash happens because it's trying to reload items in section 0 when section 0 is empty.

```
(lldb) po objectIdentifiersToIndexPaths
{
    "layer:///messages/ef51f5fa-d1b1-4a04-8fd5-da8bb1355de8" = "<NSIndexPath: 0x7b685720> {length = 2, path = 0 - 12}";
    "layer:///messages/102d9145-2184-4c77-afab-e2f8cbe9dd45" = "<NSIndexPath: 0x7b67e630> {length = 2, path = 0 - 2}";
    "layer:///messages/e8c104d0-7007-49dd-9b40-70cad3d15730" = "<NSIndexPath: 0x7b682280> {length = 2, path = 0 - 11}";
    "layer:///messages/d8f0c94f-b38d-4b64-b045-3570f076a1d0" = "<NSIndexPath: 0x7b680db0> {length = 2, path = 0 - 9}";
    "layer:///messages/c5e1fbb7-2a3b-412d-a5c0-269f2c2628b7" = "<NSIndexPath: 0x7b684860> {length = 2, path = 0 - 1}";
    "layer:///messages/5fcbf888-8730-490d-8f64-f7fb7ae4902e" = "<NSIndexPath: 0x7b69e1f0> {length = 2, path = 0 - 0}";
    "layer:///messages/d575c7a2-fe1f-4fb0-b85b-0a32b3a02bb0" = "<NSIndexPath: 0x7b677d80> {length = 2, path = 0 - 10}";
    "layer:///messages/d987abbe-1de0-4e96-82ce-1a5672461923" = "<NSIndexPath: 0x7b6820f0> {length = 2, path = 0 - 3}";
}

(lldb) po [self collectionView:self.collectionView numberOfItemsInSection:0];
<nil>
```

**Comment by davidolesch** [comment]
On lines 935-939 of ATLConversationViewController you're directly translating the LYRQueryController's indexPaths to the collectionView's indexPaths. 

```obj-c
NSDictionary *objectIdentifiersToIndexPaths = [self.conversationDataSource.queryController indexPathsForObjectsWithIdentifiers:messageIdentifiersToReload.set];
NSArray *indexPaths = [objectIdentifiersToIndexPaths allValues];
dispatch_async(dispatch_get_main_queue(), ^{
  [self.collectionView reloadItemsAtIndexPaths:indexPaths];
});
```

That doesn't look right to me based on what the [LYRQueryController documentation](https://developer.layer.com/docs/api/ios#lyrquerycontroller) says for indexPathsForObjectsWithIdentifiers. If this is incorrect it would explain the indexPath mismatch I reported in my previous comment. This causes the app to crash every time a message is sent.

**Comment by maju6406** [comment]
David - We are aware of this issue.  Try messaging another user that went through the sign up flow (not the bob or jane from the .json file).

**Comment by saoudrizwan** [comment]
@davidolesch @maju6406 I am having this same problem, but I simply deleted this line of code:
    [self.collectionView reloadItemsAtIndexPaths:indexPaths];
and it worked perfectly, is it fine if I do this or will it lead to problems?

**Comment by davidolesch** [comment]
@saoudrizwan I don't know what the underlying problems is because I can't read the source for LYRQueryController. I think the problems is either with how this project sets up the LYRQueryController or with something inside LYRQueryController.

@maju6406 creating a new user and then sending messages to it sometimes works but other times it crashes. If you're investigating this I would look at [`-[ConversationViewController conversationViewController:participantForIdentifier:]`](https://github.com/layerhq/Layer-Parse-iOS-Example/blob/master/Code/Controllers/ConversationViewController.m#L78). Why is a data source method reloading cells?

**Comment by kmahal** [comment]
@davidolesch To your second point, it reloads cells to provide asynchronous support for user management.  Without this, users would have to have all user objects in context before presenting the `ATLConversationViewController` on screen, which can be tricky to manage.

I'm looking into the other crashes today and will follow up.

**Comment by kmahal** [comment]
@davidolesch @saoudrizwan Fixed the issue.  The app should be working now, please pull down master.  It was trying to cache the `[PFUser currentUser]` when it already has it locally, causing the issue.  The `currentUser` is already always in context so adding in a check solves that problem.

**Comment by davidolesch** [comment]
@kmahal that was a tricky bug. Thanks for fixing it. I've confirmed that it's fixed.

**Comment by maxfriedman** [comment]
I just had this crash and now I have it every time I have a conversation that has more than two participants. Not sure what is wrong? Changing reloadItemsAtIndexPaths to reloadData as suggested above worked for me, but I dont want this to cause problems down the road. Ideas?
